name: CI

on:
  schedule:
  - cron: "0 0 * * 2"  # build every Tuesday

  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

  # allow manually trigger a build
  workflow_dispatch:

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
        matrix:
            # os: [ubuntu-latest, macos-latest, windows-latest]
            os: [windows-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Check env
      run: env

    - name: Build and test
      run: ./scripts/ci.sh

