name: CI

on:
  schedule:
  - cron: "0 0 * * 2"  # build every Tuesday
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: make
    - name: Test
      run: make test
